import React from 'react'
import { Segment, Header } from 'semantic-ui-react'

const BlogPreview = () => {
  return (
    <Segment>
      <Header as='h1'>asd</Header>
      <div>
        lorem ipsum dolor sit amet...
        lorem ipsum dolor sit amet...
        lorem ipsum dolor sit amet...
        lorem ipsum dolor sit amet...
        lorem ipsum dolor sit amet...
        lorem ipsum dolor sit amet...
        lorem ipsum dolor sit amet...
      </div>
    </Segment>
  )
}

export default BlogPreview